#!/bin/bash
archi="amd64"
#archi="i386"

debian_version="jessie"

dist_name="Amnesia"

iso_name="Amnesia-Debian8-amd64.iso"

boot_default="ram"
#boot_default=""
#boot_default="failsafe"

livework="./livework"
