#!/bin/bash
archi="amd64"
#archi="i386"

debian_version="stretch"

dist_name="Amnesia"

iso_name="Amnesia-Debian9-amd64.iso"

boot_default="ram"
#boot_default=""
#boot_default="failsafe"

livework="./livework"


mirror="http://ftp.us.debian.org/debian" # use by debootstrap
sources_list="deb $mirror ${debian_version} main" # if not empty, replace /etc/apt/sources.list by this content
